### ISSUE TITLE
Ground-truth file

### ISSUE THREAD

**Issue by csypeng** [ZongyueQin/Graph-Hashing#1]
Data files can be downloaded at  https://drive.google.com/open?id=1rF4QA-HDgNfFOme7M2Jw8JjYXNb6rCye

But, where can I download the ground-truth files for AIDS, LINUX, and ALCHEMY? as they are needed by checkAcc

**Comment by ZongyueQin** [comment]
You can compute it using BSS-GED or other exact GED solvers.
